#
#  开发环境配置文件
#  上线需切换至 pro
#
server:
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
    max-http-form-post-size: 20MB
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  freemarker:
    settings:
      number_format: 0.##
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  #数据源
  datasource:
    url: jdbc:mysql://172.168.95.9:3306/lsoa?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rjgs@2016
    # driver-class需要注意mysql驱动的版本(com.mysql.cj.jdbc.Driver 或 com.mysql.jdbc.Driver)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 10
      # 连接池的最小空闲数量
      min-idle: 10
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 1 from dual
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: true
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 开启filters的stat监控统计插件，下边进行添加监控配置
      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: xujian
        login-password: 123456
        # IP白名单
        allow: 192.168.111.10
        # IP黑名单（共同存在时，deny优先于allow）
        deny:

  tomcat:
    test-while-idle: true

  #redis配置
  redis:
    database: 4
    host: 172.168.80.6
    password: jsdc@0516
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    timeout: 10000

  jpa:
    #打印sql
    show-sql: true
    hibernate:
      naming:
        #表的命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #自动建表
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#elasticsearch:
#  host : 172.168.95.9
#  port : 9200
management:
  health:
    elasticsearch:
      enabled: false
mybatis-plus:
  #  type-aliases-package: com.jsdc.tzxtgl.model
  #  mapper-locations: com/jsdc/zhly/mapper/xml/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略
    field-strategy: 1
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mybatis:
    configuration:
      map-underscore-to-camel-case: false

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    org.apache.ibatis: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: debug
    root: info
    com.jsdc: debug
  config: classpath:config/logback-spring.xml

#sa-token和redis配置
sa-token:
  alone-redis:
    database: 4
    # Redis服务器地址
    host: 172.168.80.6
    #    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: jsdc@0516
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0